### ISSUE TITLE
[Feat] 모달 컴포넌트 병합 - 저장_삭제_수정

### ISSUE THREAD

**Issue by yong313** [hinyc/wanted-codestates-project-10-8#30]
### ISSUE
- Group: client, server, sr
- Type: bug, feature, delete
- Detail: fix actions from client redux

### TODO
 - [ ] 모달 컴포넌트 병합
 - [ ] 나의 휴양지 저장
 - [ ] 나의 휴양지 삭제
 - [ ] 나의 휴양지 수정
