### ISSUE TITLE
[Feat] 모달 컴포넌트 구현

### ISSUE THREAD

**Issue by yong313** [hinyc/wanted-codestates-project-10-8#5]
### ISSUE
- Group: client, server, sr
- Type: bug, feature, delete
- Detail: fix actions from client redux

### TODO
 - [x] 저장 및 수정 모달 컴포넌트 구현
 - [x] 모달 영역 밖 클릭 시 모달 닫기
 - [x] 위에서 아래로 에니메이션 적용
