### ISSUE TITLE
[feat] 메인페이지 컴포넌트 구현 - 마크업 & 스타일링

### ISSUE THREAD

**Issue by SpearJin** [hinyc/wanted-codestates-project-10-8#8]
### ISSUE
- Group: client, server, sr
- Type: bug, feature, delete
- Detail: fix actions from client redux

### TODO
 - [ ] 메인 페이지 컴포넌트 만들기
 - [ ] 메인 페이지 컴포넌트 마크업
 - [ ] 메인 페이지 컴포넌트 스타일링
 - [ ] 메인 페이지 컴포넌트 기능 구현
